console:
  description: Program-Y Console Client
  bot:  bot
  prompt: ">>>"

  scheduler:
    name: Scheduler1
    debug_level: 50
    add_listeners: False
    remove_all_jobs: False

  storage:
      entities:
          users: mongo
          linked_accounts: mongo
          links: mongo

          categories: mongo
          errors: mongo
          duplicates: mongo
          learnf: mongo
          conversations:   mongo

          maps: mongo
          sets: mongo
          rdf: mongo

          denormal: mongo
          normal: mongo
          gender: mongo
          person: mongo
          person2: mongo
          regex_templates: mongo

          properties: mongo
          variables: mongo

          twitter: mongo

          spelling_corpus: mongo
          license_keys: mongo

          template_nodes: mongo
          pattern_nodes: mongo

          binaries: mongo
          braintree: mongo

          preprocessors: mongo
          postprocessors: mongo

          usergroups: mongo

      stores:

          mongo:
              type:   mongo
              config:
                  url: mongodb://localhost:32768/
                  database: programy
                  drop_all_first: false

#####################################################################################################
#

bot:
    brain: brain

    initial_question: Hi, how can I help you today?
    initial_question_srai: YINITIALQUESTION
    default_response: Sorry, I don't have an answer for that!
    default_response_srai: YEMPTY
    empty_string: YEMPTY
    exit_response: So long, and thanks for the fish!
    exit_response_srai: YEXITRESPONSE

    override_properties: true

    max_question_recursion: 1000
    max_question_timeout: 60
    max_search_depth: 100
    max_search_timeout: 60

    spelling:
      load: true
      classname: programy.spelling.norvig.NorvigSpellingChecker
      check_before: false
      check_and_retry: false

    conversations:
      save: true
      load: false


#####################################################################################################
#

brain:

    # Overrides
    overrides:
      allow_system_aiml: true
      allow_learn_aiml: true
      allow_learnf_aiml: true

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown

    # Binary
    binaries:
      save_binary: false
      load_binary: false
      load_aiml_on_binary_fail: false

    debugfiles:
      save-errors: true
      save-duplicates: true

    # Braintree
    braintree:
      create: False

    services:
        REST:
            classname: programy.services.rest.GenericRESTService
            method: GET
            host: 0.0.0.0
        Pannous:
            classname: programy.services.pannous.PannousService
            url: http://weannie.pannous.com/api
        Pandora:
            classname: programy.services.pandora.PandoraService
            url: http://www.pandorabots.com/pandora/talk-xml
        Wikipedia:
            classname: programy.services.wikipediaservice.WikipediaService
        DuckDuckGo:
            classname: programy.services.duckduckgo.DuckDuckGoService
            url: http://api.duckduckgo.com

    security:
        authentication:
            classname: programy.security.authenticate.passthrough.BasicPassThroughAuthenticationService
            denied_srai: AUTHENTICATION_FAILED
        authorisation:
            classname: programy.security.authorise.usergroupsauthorisor.BasicUserGroupAuthorisationService
            denied_srai: AUTHORISATION_FAILED

    oob:
      default:
        classname: programy.oob.default.DefaultOutOfBandProcessor
      alarm:
        classname: programy.oob.alarm.AlarmOutOfBandProcessor
      camera:
        classname: programy.oob.camera.CameraOutOfBandProcessor
      clear:
        classname: programy.oob.clear.ClearOutOfBandProcessor
      dial:
        classname: programy.oob.dial.DialOutOfBandProcessor
      dialog:
        classname: programy.oob.dialog.DialogOutOfBandProcessor
      email:
        classname: programy.oob.email.EmailOutOfBandProcessor
      geomap:
        classname: programy.oob.map.MapOutOfBandProcessor
      schedule:
        classname: programy.oob.schedule.ScheduleOutOfBandProcessor
      search:
        classname: programy.oob.search.SearchOutOfBandProcessor
      sms:
        classname: programy.oob.sms.SMSOutOfBandProcessor
      url:
        classname: programy.oob.url.URLOutOfBandProcessor
      wifi:
        classname: programy.oob.wifi.WifiOutOfBandProcessor

    dynamic:
        variables:
            gettime: programy.dynamic.variables.datetime.GetTime
        sets:
            numeric: programy.dynamic.sets.numeric.IsNumeric
            roman:   programy.dynamic.sets.roman.IsRomanNumeral
        maps:
            romantodec: programy.dynamic.maps.roman.MapRomanToDecimal
            dectoroman: programy.dynamic.maps.roman.MapDecimalToRoman

